import React, { Component } from 'react'
import { StyleSheet, Dimensions } from 'react-native'
const {width,scale} = Dimensions.get('window');
const s = width / 640;
var chat = StyleSheet.create({
    header:{
        width:width,
        height:50,
        justifyContent:'center',
        alignItems:'center'
    },
    back:{
        position:'absolute',
        left:5,
        top:5
    },
    icons:{
        width:width,
        paddingTop:10,
        paddingBottom:10,
        backgroundColor:'#fff',
        // borderBottomWidth:15,
        // borderBottomColor:'#f0f0f0',
        flexDirection:'row',
        height:60
    },
    bottom:{
        justifyContent:'center',
        alignItems:'center'
    },
    bottomtext:{
        paddingTop:50,
        color:'#8bcca1'
    },
    images1:{
        resizeMode:'contain',
        width:35,
        height:35,
        position:'absolute',
        right:10,
        top:5

    },
    images2:{
        resizeMode:'contain',
        width:35,
        height:35,
        position:'absolute',
        right:60,
        top:5
    },
    images3:{
        resizeMode:'contain',
        width:35,
        height:35,
        position:'absolute',
        right:110,
        top:5
    },
    images:{
        width:35,
        height:35,
        resizeMode:'contain'
    },
    mebox:{
        width:width,
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:10,
        borderTopColor:'#f0f0f0',
        borderTopWidth:15
    },
    meheader:{
        width:width,
        flexDirection:'row',
    },
    meheaderimage:{
        width:55,
        height:55,
        borderRadius:27.5,
        backgroundColor:'#000',
        marginLeft:20,
        marginBottom:10
    },
    meheadertext:{
        marginLeft:10,
        marginTop:10,
        fontSize:16,
        fontWeight:'500'
    },
    imagess:{
        width:55,
        height:55,
        resizeMode:'contain'
    },
    mecontents:{
        width:width,
        justifyContent:'center',
        alignItems:'center'

    },
    mecontent:{
        width:width*0.9,
        backgroundColor:'#f5f6f8',
        paddingTop:10,
        paddingBottom:10,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    mecontentss:{
        width:width*0.9,
        backgroundColor:'#f5f6f8',
        paddingTop:10,
        paddingBottom:10,
        justifyContent:'center',
        alignItems:'center',
    },
    mecontenttext:{
        fontSize:15,
    },
    otherbox:{
        width:width,
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:10,
        borderTopColor:'#f0f0f0',
        borderTopWidth:15
    },
    otherheader:{
        width:width,
        flexDirection:'row',
        height:65
    },
    otherheaderimage:{
        width:55,
        height:55,
        borderRadius:27.5,
        backgroundColor:'#000',
        position:'absolute',
        right:20,  
    },
    otherheadertext:{
        fontSize:16,
        fontWeight:'500',
        position:'absolute',
        right:85,
        top:10
    },
    othercontents:{
        width:width,
        justifyContent:'center',
        alignItems:'center'
    },
    othercontent:{
        width:width*0.9,
        backgroundColor:'#f5f6f8',
        paddingTop:10,
        paddingBottom:10,
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    othercontentss:{
        width:width*0.9,
        backgroundColor:'#f5f6f8',
        paddingTop:10,
        paddingBottom:10,
        justifyContent:'center',
        alignItems:'center',
    },
    othercontenttext:{
        fontSize:15
    },
    friendbox:{
        width:width,
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:20,
        borderTopColor:'#f0f0f0',
        borderTopWidth:15
    },
    lock:{
        marginLeft:10
        // position:'absolute',
        // right:20,
        // bottom:15
    },
    loc:{
        width:25,
        height:25,
        resizeMode:'contain'
    },
    reason:{
        marginTop:10,
        marginBottom:5,
        backgroundColor:'#8bcca1',
        paddingTop:5,
        paddingBottom:5,
        width:width*0.75,
        textAlign:'center'
    },
    mesend:{
        width:width,
        paddingTop:10,
        paddingBottom:10,
        backgroundColor:'#8bcca1',
        justifyContent:'center',
        alignItems:'center',
        // marginTop:10
    },
    mesendtext:{
        color:'white',
        fontSize:17
    },
    mereply:{
        width:width,
        borderTopWidth:2,
        borderTopColor:'#8bcca1',
        flexDirection:'row'
    },
    button:{
        width:width*0.5,
        backgroundColor:'#fff',
        paddingTop:10,
        paddingBottom:10,
        color:'#8bcca1'
    },
    button1:{
        paddingBottom:10,
        paddingTop:10,
        width:width*0.5,
        backgroundColor:'#8bcca1',
        color:'#fff'
    }

})

module.exports = chat;